### ISSUE TITLE
y/ssl error when using npm to install ewd.js

### ISSUE THREAD

**Issue by wlf211** [robtweed/ewd.js#16]
Hi, excited to start working with ewd.js but having trouble installing on my ubuntu virtual machine running on virtualbox.

I get the error below:

Any idea how to resolve?

Thanks,

Bill

nstall EWD.js to directory path (/home/wfrey): y
installing EWD.js to y
Move Directory from y/node_modules/ewdjs/essentials/www to y/www
Warning: y/node_modules/ewdjs/essentials/www no longer exists in the ewd.js module directory

fs.js:654
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory 'y/ssl'
    at Object.fs.mkdirSync (fs.js:654:18)
    at installEWD (/home/wfrey/node_modules/ewdjs/essentials/install.js:149:35)
    at /home/wfrey/node_modules/ewdjs/essentials/install.js:279:3
    at Interface._onLine (readline.js:201:5)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)
    at ReadStream.emit (events.js:98:17)
    at emitKey (readline.js:1096:12)
    at ReadStream.onData (readline.js:841:14)

npm ERR! ewdjs@0.100.0 postinstall: `node essentials/install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ewdjs@0.100.0 postinstall script.
npm ERR! This is most likely a problem with the ewdjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node essentials/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls ewdjs
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/home/wfrey/.nvm/v0.10.38/bin/node" "/home/wfrey/.nvm/v0.10.38/bin/npm" "install" "ewdjs"
npm ERR! cwd /home/wfrey
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by robtweed** [comment]
Bill

Best to ask support questions in the EWD Google Group at https://groups.google.com/forum/#!forum/enterprise-web-developer-community

However to answer your question, to accept the default path for EWD.js installation, just hit Enter, not y.  By typing y it thinks that's the path you want to install into

Rob
