### ISSUE TITLE
Unable to start child process in debug mode

### ISSUE THREAD

**Issue by mark-fisher** [robtweed/ewd.js#9]
I am attempting to step through ewd.js using the node-debug package. I noticed that line 2007, **ewd.startChildProcess(0);**, does not pass the second parameter which is the debug flag. Therefore, it appears that the only way to start a child process in debug mode is to set the second parameter to true. I tested this and verified that I could step through ewdChildProcess.js on port 5860.

**Comment by rgaber** [comment]
When trying to debug the ewd-federator in this manner, I get to line 1207 of ewdrest.js, which starts the childProcesses, they never start and the debugger simply stops.  The console screen is showing
the following, the child processes never start.

C:\ewdjs>node-debug --web-port=8081 --save-live-edit ewdStartFederator_soap.js
Node Inspector is now available from http://127.0.0.1:8081/debug?ws=127.0.0.1:8081&port=5858
Debugging `ewdStartFederator_soap.js`

debugger listening on port 5858

******************************************************
**** ewd-federator: Build 14 (22 May 2015) *******
******************************************************

Started: Wed, 10 Jun 2015 20:28:52 GMT
Master process: 86132
2 child Node processes will be started...
debugger listening on port 5858  (This is where is sits forever)

I tried using the ewdFederatorMgr to start a childProcess in debug mode, but it does not behave in the same manner as the ewdMonitor app, which does start them in debug mode.

**Comment by robtweed** [comment]
Hi Roy

I don’t think I fully implemented the debug mode for ewdFederatorMgr or ewd-federator

Rob
